---

name: checks

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:


env:
  PRE_COMMIT_VERSION: "2.16.0"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install pre-commit $PRE_COMMIT_VERSION
        run: pip install pre-commit==$PRE_COMMIT_VERSION
      - name: Run pre-commit
        run: pre-commit run --all-files
